<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ugv_imu_bridge</name>
  <version>0.0.1</version>
  <description>Bridges Waveshare UGV ESP32 UART IMU stream to a ROS2 sensor_msgs/Imu topic.</description>
  <maintainer email="murshid.ahnaf@gmail.com">Ahnaf</maintainer>
  <license>GPL-3.0</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>python3-serial</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
